# All course-related operations

# Queries
query getCourses($semester: String!) {
  courses {
    id
    name
    semester
    description
    createdAt
    updatedAt
    students {
      id
    }
  }
}

query getCourse($id: ID!) {
  course(id: $id) {
    id
    name
    semester
    description
    createdAt
    updatedAt
    staff {
      id
      firstName
      lastName
      title
    }
    students {
      id
      firstName
      lastName
    }
  }
}

query getStudentCourses($studentId: ID!) {
  studentCourses(studentId: $studentId) {
    id
    name
    semester
    description
  }
}

query getStaffCourses($staffId: ID!) {
  staffCourses(staffId: $staffId) {
    id
    name
    semester
    description
  }
}

# Mutations
mutation createCourse($input: NewCourse!) {
  createCourse(input: $input) {
    id
    name
    semester
    description
  }
}

mutation updateCourse($id: ID!, $input: UpdateCourse!) {
  updateCourse(id: $id, input: $input) {
    id
    name
    semester
    description
  }
}

mutation deleteCourse($id: ID!) {
  deleteCourse(id: $id)
}

mutation addStudentToCourse($courseId: ID!, $studentId: ID!) {
  addStudentToCourse(courseId: $courseId, studentId: $studentId)
}

mutation removeStudentFromCourse($courseId: ID!, $studentId: ID!) {
  removeStudentFromCourse(courseId: $courseId, studentId: $studentId)
}

mutation addStaffToCourse($courseId: ID!, $staffId: ID!) {
  addStaffToCourse(courseId: $courseId, staffId: $staffId)
}

mutation removeStaffFromCourse($courseId: ID!, $staffId: ID!) {
  removeStaffFromCourse(courseId: $courseId, staffId: $staffId)
} 